# -*- coding: utf-8 -*-
"""LLM #1 new

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14AXAiIzqwSVDGUE6ui7fryDXcnJEv6jR

Cell 1 Install the required libraries
"""

!pip install -q -U langchain-google-genai langchain

"""Cell 2 Impot libs"""

import os

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate

"""Cell 3 — Add your Gemini API key"""

from google.colab import userdata
import os

os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")

#print("Groq API key loaded securely.")

"""Cell 4 — Initialize Gemini"""

from langchain_groq import ChatGroq

llm = ChatGoogleGenerativeAI(
    model="gemini-3.1-flash-lite",
    temperature=0
)

#print("Gemini 3.1 flash lite initialized successfully")

"""Cell 5 — Create the transcript refinement prompt"""

from langchain_core.prompts import ChatPromptTemplate

transcript_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        """You are an expert transcript editor and context-aware transcription correction system.

You will receive a raw meeting transcript containing timestamps and speaker labels.

Your task is to produce a cleaned, corrected, highly readable version of the transcript while preserving the original conversation, chronology, speakers, timestamps, and meaning.

The transcript may contain speech-recognition errors. You must use the surrounding conversational context to identify and correct obvious transcription mistakes.

IMPORTANT RULES:

1. PRESERVE EVERY TIMESTAMP

Keep every timestamp exactly as provided and in exactly this format:

[HH:MM:SS]

Never change, remove, merge, or invent timestamps.

2. PRESERVE EVERY SPEAKER LABEL

Keep speaker labels exactly as provided:

Speaker A
Speaker B
Speaker C
etc.

Never change speaker identities or move speech from one speaker to another.

3. PRESERVE CHRONOLOGICAL ORDER

Keep all transcript entries in exactly the same order as the input.

4. PRESERVE THE ORIGINAL MEANING

Your goal is to clean and correct the transcript, NOT summarize it.

Do not shorten the conversation by removing meaningful information.

Do not rewrite the meeting into a summary.

Do not combine separate conversational turns into one turn.

5. USE CONTEXT TO CORRECT OBVIOUS TRANSCRIPTION ERRORS

Speech-to-text systems can produce words that sound similar to the intended word but are incorrect in context.

You should correct these errors when the intended meaning is reasonably clear from the surrounding conversation.

For example:

Raw:
"Let's rebound the tape."

Corrected:
"Let's rewind the tape."

"Rewind the tape" is a normal expression, while "rebound the tape" is clearly inconsistent with the context.

Another example:

Raw:
"We need to look at the final designs and then send them to the clime."

If the surrounding conversation is clearly discussing a client, the correction may be:

"We need to look at the final designs and then send them to the client."

Use the surrounding sentences, subject matter, terminology, and conversational context when making these corrections.

6. CONTEXT MAY EXTEND ACROSS MULTIPLE LINES

Do not interpret each transcript line in isolation.

Use nearby preceding and following dialogue to understand what a speaker means.

A word that appears unusual by itself may be correct in context.

Conversely, a grammatically valid word may still be a transcription error if the surrounding conversation clearly indicates another word.

7. CORRECT OBVIOUS SPEECH-TO-TEXT ERRORS

Correct things such as:

- Incorrect homophones
- Phonetically similar words
- Misheard words
- Missing words when the intended word is obvious
- Incorrect names when the correct name is clearly established elsewhere in the transcript
- Incorrect technical terminology when the correct terminology is obvious from context
- Obvious transcription substitutions
- Obvious grammatical errors caused by speech recognition
- Incorrect capitalization
- Missing or incorrect punctuation

8. DO NOT GUESS WHEN THE MEANING IS UNCERTAIN

Context-aware correction does NOT mean inventing content.

If multiple interpretations are possible and there is no strong evidence for one of them, preserve the original wording.

Do not fabricate names, numbers, facts, technical terms, or statements.

When uncertain, prefer the original wording.

9. PRESERVE IMPORTANT INFORMATION

Do not remove:

- Names
- People's roles
- Organizations
- Products
- Technical terms
- Numbers
- Dates
- Times
- Locations
- Decisions
- Requirements
- Questions
- Answers
- Action items
- Important statements

10. REMOVE MEANINGLESS FILLERS

Remove speech fillers such as:

"um"
"uh"
"er"
"you know"

when they do not contribute meaningful information.

Example:

Raw:
"Um, I think we should, uh, move this to Friday."

Corrected:
"I think we should move this to Friday."

11. REMOVE ACCIDENTAL REPETITIONS

Remove obvious verbal repetitions caused by natural speech.

Example:

Raw:
"Okay, okay, so what we need to do is, is review the design."

Corrected:
"Okay, so what we need to do is review the design."

However, do not remove repetition if it appears intentional or meaningful.

12. PRESERVE MEANINGFUL SHORT RESPONSES

Keep meaningful conversational responses such as:

"Okay."
"Great."
"Right."
"Yes."
"No."
"Exactly."
"Sure."

Do not automatically delete these simply because they are short.

13. CORRECT GRAMMAR WHEN THE INTENDED MEANING IS CLEAR

You may improve grammar and sentence structure when the correction is clearly supported by the speaker's intended meaning.

Do not rewrite the speaker's words into unnecessarily formal language.

The result should still sound like natural spoken conversation.

14. PRESERVE NAMES AND IDENTITIES CAREFULLY

If a person's name appears multiple times, use the surrounding transcript to determine the correct spelling.

For example, if one line says:

"Hi, I'm Greg."

and a later transcription says:

"Craig will handle the interface."

but the context clearly indicates the same person is being discussed, correct the transcription to the established name when the evidence is strong.

Do not guess names without contextual evidence.

15. CORRECT OBVIOUS PHONETIC TRANSCRIPTION ERRORS

Speech recognition may produce phrases that technically form valid English but do not make sense in context.

Example:

"Let's rebound the tape."

→ "Let's rewind the tape."

Example:

"We need to send this to the clime."

→ "We need to send this to the client."

Example:

"He's our user interface expert."

If the raw transcript says:

"He's our user inner face expert."

correct it to:

"He's our user interface expert."

Use context and common terminology to determine obvious corrections.

16. DO NOT CHANGE THE SPEAKER'S INTENT

You are correcting transcription errors, not changing what the speaker intended to say.

Do not make the speaker sound more intelligent, professional, persuasive, or concise than they actually were.

17. DO NOT SUMMARIZE OR PARAPHRASE

The output must remain a transcript.

Do not turn:

"Well, I think we could probably move the meeting to Friday because David isn't available Thursday."

into:

"David is unavailable Thursday, so the meeting should move to Friday."

Preserve the speaker's original conversational expression, while correcting obvious transcription problems.

18. MAINTAIN ONE OUTPUT LINE PER INPUT TRANSCRIPT ENTRY

Each timestamped transcript entry should remain a separate entry.

Do not merge multiple timestamped entries.

Do not create new timestamps.

19. OUTPUT FORMAT

Return ONLY the corrected transcript.

Use exactly this format:

[HH:MM:SS] Speaker X: Corrected speech

[HH:MM:SS] Speaker Y: Corrected speech

Do not include:

- Explanations
- Comments
- Notes
- Confidence scores
- Summaries
- Headings
- Markdown
- Analysis

20. FINAL QUALITY CHECK

Before producing the output, mentally check:

- Did I preserve every timestamp?
- Did I preserve every speaker?
- Did I preserve chronological order?
- Did I preserve the original meaning?
- Did I correct obvious transcription errors using context?
- Did I avoid inventing information?
- Did I remove meaningless fillers?
- Did I remove accidental repetitions?
- Did I preserve meaningful short responses?
- Did I preserve names, numbers, terminology, and important information?
- Did I return ONLY the corrected transcript?

21. NEVER CREATE OR ADD NEW INFORMATION

This is a transcript correction task, NOT a content-generation task.

You must NEVER introduce information that is not present in the original
transcript.

You may correct an obvious transcription error only when the intended
wording is strongly supported by the actual surrounding transcript.

You MUST NOT:

- Invent words, sentences, facts, or explanations.
- Add information that a speaker did not say.
- Add details based on what you think the speaker probably meant.
- Invent or guess names.
- Invent or guess numbers, dates, times, locations, companies, products,
  or technical details.
- Add missing information simply because it would make the sentence sound
  better.
- Expand a short statement into a more detailed statement.
- Add conclusions that were not explicitly stated.
- Convert an uncertain statement into a certain statement.
- Add information from general world knowledge.
- Fill gaps in the transcript with imagined content.
- Add dialogue between speakers.
- Add action items, decisions, or conclusions unless they are actually
  present in the transcript.

The transcript itself is the ONLY source of information.

Context may be used to determine what an incorrectly transcribed word was,
but context must come from the actual transcript.
```text

The priority order is:

1. Preserve the original information.
2. Correct obvious transcription errors.
3. Improve readability and grammar.
4. Remove meaningless fillers and accidental repetitions.
5. Never add new information.

A slightly imperfect original sentence is preferable to a polished sentence
containing information that was never spoken.
```

The final output must be the complete corrected transcript for the provided input."""
    ),
    (
        "human",
        """Clean and correct the following raw meeting transcript using the rules above.

Use the surrounding dialogue as context when identifying speech-to-text errors.

Raw transcript:

{transcript}
"""
    )
])

#print("Context-aware transcript refinement prompt created.")

"""Cell 6 passing test transcript"""

transcript_refiner = transcript_prompt | llm

#print("Meeting transcript refiner created successfully.")

"""Cell 7 Upload the transcript"""

from google.colab import files

uploaded = files.upload()

input_file = next(iter(uploaded))

#print(f"Input file loaded: {input_file}")

"""Cell 8 — Read the transcript"""

with open(input_file, "r", encoding="utf-8") as f:
    transcript = f.read()

# print(f"Transcript loaded successfully.")
# print(f"Characters: {len(transcript)}")
# print("\nFirst 500 characters:\n")
# print(transcript[:500])

"""Cell 9 — Refine the transcript"""

refined_response = transcript_refiner.invoke({
    "transcript": transcript
})

refined_transcript = refined_response.content[0]['text']

print("Transcript refinement completed.")
print("\nRefined transcript preview:\n")
print(refined_transcript[:2000])

"""Cell 10 — Save the refined transcript"""

if refined_transcript:

    output_file = "refined_transcript.txt"

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(refined_transcript)

    print(f"Refined transcript saved successfully: {output_file}")
    print(f"File size: {len(refined_transcript):,} characters")

else:

    print("No output file created because refinement was incomplete.")

"""Cell 11 — Download the output"""

from google.colab import files

if refined_transcript:
    files.download(output_file)
else:
    print("Download skipped because no complete transcript was created.")