# -*- coding: utf-8 -*-
"""ML_BOOtcamp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z5sqCuaXKeqtFRjWd_hV2R5Y0uvpEVPb
"""

!pip install whisperx

!pip install ffmpeg

!pip install setuptools-rust

import gc, re, json, torch, whisperx
from google.colab import userdata
from whisperx.diarize import DiarizationPipeline

HF_TOKEN = userdata.get("HF_TOKEN")
device = "cuda" if torch.cuda.is_available() else "cpu"
ctype = "float16" if device == "cuda" else "int8"
path = "ES2003a.Mix-Headset.wav"

# Optional context (names/jargon). Leave "" for none.
context = "Meeting participants: Laura, David, Andrew, Craig. Topic: remote control design, prices in euros."

# ---------- helper functions ----------
TERM = re.compile(r"[.?!…]+[\"')]*$")
is_end = lambda w: bool(TERM.search(w["w"]))

def build_turns(result, min_words=2):
    """Group aligned words into speaker turns: [[speaker, [word dicts]], ...]
    word dict: w=text, s/e=word start/end (None if unaligned), ss/se=segment start/end (fallback)."""
    turns = []
    for seg in result["segments"]:
        last = seg.get("speaker", "UNKNOWN")
        ss, se = seg.get("start"), seg.get("end")
        words = seg.get("words") or [{"word": seg["text"].strip(), "speaker": last}]
        for w in words:
            spk = w.get("speaker", last)            # unaligned tokens inherit previous speaker
            last = spk
            item = {"w": w["word"], "s": w.get("start"), "e": w.get("end"), "ss": ss, "se": se}
            if turns and turns[-1][0] == spk: turns[-1][1].append(item)
            else: turns.append([spk, [item]])
    i = 1                                            # smooth 1-word flickers: A B A -> A
    while i < len(turns) - 1:
        if len(turns[i][1]) < min_words and turns[i-1][0] == turns[i+1][0]:
            turns[i-1][1] += turns[i][1] + turns[i+1][1]
            del turns[i:i+2]
        else:
            i += 1
    return turns

def merge_same(turns):
    out = []
    for s, w in turns:
        if not w: continue
        if out and out[-1][0] == s: out[-1][1] += w
        else: out.append([s, list(w)])
    return out

def snap_boundaries(turns, max_move=3):
    """Fix 1-3 word speaker flips that happen mid-sentence."""
    turns = merge_same(turns); i = 0
    while i < len(turns) - 1:
        p, n = turns[i][1], turns[i+1][1]; moved = False
        if p and n and not is_end(p[-1]):
            k = max([j for j, w in enumerate(p) if is_end(w)], default=-1)
            F = p[k+1:]
            c = next((j for j, w in enumerate(n) if is_end(w)), None)
            C = n[:c+1] if c is not None else None
            if C is not None and min(len(F), len(C)) <= max_move:
                if len(C) <= len(F): turns[i][1] = p + C; turns[i+1][1] = n[len(C):]
                else:                turns[i][1] = p[:k+1]; turns[i+1][1] = F + n
                moved = True
        if moved: turns = merge_same(turns); i = max(0, i-1)
        else: i += 1
    return turns

def fmt_time(t):
    t = max(0, int(round(t)))
    h, rem = divmod(t, 3600); m, s = divmod(rem, 60)
    return f"{h}:{m:02d}:{s:02d}" if h else f"{m:02d}:{s:02d}"

def to_records(turns):
    """Turns -> list of dicts: speaker, start, end (seconds), text."""
    recs = []
    for spk, words in turns:
        starts = [w["s"] for w in words if w["s"] is not None]
        ends   = [w["e"] for w in words if w["e"] is not None]
        start = min(starts) if starts else next((w["ss"] for w in words if w["ss"] is not None), 0.0)
        end   = max(ends)   if ends   else next((w["se"] for w in reversed(words) if w["se"] is not None), start)
        recs.append({"speaker": spk, "start": round(start, 2), "end": round(end, 2),
                     "text": " ".join(w["w"] for w in words).strip()})
    return recs

def format_timed(recs):
    return "\n".join(f"[{fmt_time(r['start'])} - {fmt_time(r['end'])}] {r['speaker']}: {r['text']}" for r in recs)

def format_plain(recs):      # format used by eval_transcript.py
    return "\n".join(f"[{r['speaker']}] {r['text']}" for r in recs)

# ---------- pipeline ----------
# 1) Transcribe
model = whisperx.load_model(
    "large-v3", device, compute_type=ctype, language="en",
    asr_options={"initial_prompt": context or None},
    # vad_options={"vad_onset": 0.35, "vad_offset": 0.3},   # uncomment to test lower VAD (variant B)
)
audio = whisperx.load_audio(path)
result = model.transcribe(audio, batch_size=16)
del model; gc.collect()
if device == "cuda": torch.cuda.empty_cache()

# 2) Align (gives word-level timestamps)
align_model, metadata = whisperx.load_align_model(language_code="en", device=device)
result = whisperx.align(result["segments"], align_model, metadata, audio, device)

# 3) Diarize + assign speakers to words
diarize_model = DiarizationPipeline(token=HF_TOKEN, device=device)
diarize_segments = diarize_model(audio, min_speakers=2, max_speakers=8)
result = whisperx.assign_word_speakers(diarize_segments, result, fill_nearest=True)

# 4) Turns -> fix mid-sentence flips -> records with timestamps
records = to_records(snap_boundaries(build_turns(result)))

timed_transcript = format_timed(records)     # for display / the app / the LLM stages
plain_transcript = format_plain(records)     # for eval_transcript.py
print(timed_transcript)

# 5) Save outputs
with open("transcript_A_timed.txt", "w") as f: f.write(timed_transcript)
with open("transcript_A.txt", "w") as f:      f.write(plain_transcript)
with open("transcript_A.json", "w") as f:     json.dump(records, f, indent=2)

import os, subprocess, json
from google.colab import files

ALLOWED_EXT = {".wav", ".mp3", ".m4a", ".flac", ".ogg", ".opus", ".aac", ".wma", ".mp4", ".webm", ".mkv", ".mov"}
MAX_MB = 500

class AudioError(Exception):
    """Raised with a user-friendly message when the audio cannot be processed."""

def validate_audio(path, min_seconds=1.0):
    """Check extension, size and decodability. Returns duration in seconds or raises AudioError."""
    if not path or not os.path.exists(path):
        raise AudioError("No file was provided.")
    ext = os.path.splitext(path)[1].lower()
    if ext not in ALLOWED_EXT:
        raise AudioError(f"Unsupported file type '{ext or 'none'}'. Please upload one of: "
                         + ", ".join(sorted(e.lstrip('.') for e in ALLOWED_EXT)) + ".")
    size = os.path.getsize(path)
    if size == 0:
        raise AudioError("The file is empty (0 bytes).")
    if size > MAX_MB * 1024 * 1024:
        raise AudioError(f"The file is too large ({size/1e6:.0f} MB). Maximum is {MAX_MB} MB.")
    try:
        out = subprocess.run(
            ["ffprobe", "-v", "error", "-select_streams", "a:0", "-show_entries", "format=duration",
             "-of", "json", path], capture_output=True, text=True, timeout=60)
    except FileNotFoundError:
        raise AudioError("ffmpeg/ffprobe is not installed on this machine.")
    except subprocess.TimeoutExpired:
        raise AudioError("Timed out while reading the file. It may be corrupted.")
    if out.returncode != 0:
        raise AudioError("The file could not be read as audio. It may be corrupted or not a real audio file.")
    try:
        duration = float(json.loads(out.stdout).get("format", {}).get("duration"))
    except (TypeError, ValueError):
        raise AudioError("No audio track was found in this file.")
    if duration < min_seconds:
        raise AudioError(f"The audio is too short ({duration:.1f}s) to transcribe.")
    return duration

def get_audio_from_user():
    """Opens the Colab upload dialog, validates the file, returns its path."""
    uploaded = files.upload()                       # shows a "Choose files" button
    if not uploaded:
        raise AudioError("No file was uploaded.")
    if len(uploaded) > 1:
        print(f"Multiple files uploaded; using the first one: {next(iter(uploaded))}")
    path = next(iter(uploaded))                     # Colab saves it in the current folder
    duration = validate_audio(path)
    print(f"✅ Loaded '{path}' ({duration/60:.1f} min)")
    return path

try:
    path = get_audio_from_user()
except AudioError as e:
    path = None
    print(f"❌ {e}")

import gc, re, json, torch, whisperx
from google.colab import userdata
from whisperx.diarize import DiarizationPipeline
if path is None:
  raise SystemExit("Please upload a valid audio file first (run the upload cell).")


HF_TOKEN = userdata.get("HF_TOKEN")
device = "cuda" if torch.cuda.is_available() else "cpu"
ctype = "float16" if device == "cuda" else "int8"

# ---------- helper functions ----------
TERM = re.compile(r"[.?!…]+[\"')]*$")
is_end = lambda w: bool(TERM.search(w["w"]))

def build_turns(result, min_words=2):
    """Group aligned words into speaker turns: [[speaker, [word dicts]], ...]
    word dict: w=text, s/e=word start/end (None if unaligned), ss/se=segment start/end (fallback)."""
    turns = []
    for seg in result["segments"]:
        last = seg.get("speaker", "UNKNOWN")
        ss, se = seg.get("start"), seg.get("end")
        words = seg.get("words") or [{"word": seg["text"].strip(), "speaker": last}]
        for w in words:
            spk = w.get("speaker", last)            # unaligned tokens inherit previous speaker
            last = spk
            item = {"w": w["word"], "s": w.get("start"), "e": w.get("end"), "ss": ss, "se": se}
            if turns and turns[-1][0] == spk: turns[-1][1].append(item)
            else: turns.append([spk, [item]])
    i = 1                                            # smooth 1-word flickers: A B A -> A
    while i < len(turns) - 1:
        if len(turns[i][1]) < min_words and turns[i-1][0] == turns[i+1][0]:
            turns[i-1][1] += turns[i][1] + turns[i+1][1]
            del turns[i:i+2]
        else:
            i += 1
    return turns

def merge_same(turns):
    out = []
    for s, w in turns:
        if not w: continue
        if out and out[-1][0] == s: out[-1][1] += w
        else: out.append([s, list(w)])
    return out

def snap_boundaries(turns, max_move=3):
    """Fix 1-3 word speaker flips that happen mid-sentence."""
    turns = merge_same(turns); i = 0
    while i < len(turns) - 1:
        p, n = turns[i][1], turns[i+1][1]; moved = False
        if p and n and not is_end(p[-1]):
            k = max([j for j, w in enumerate(p) if is_end(w)], default=-1)
            F = p[k+1:]
            c = next((j for j, w in enumerate(n) if is_end(w)), None)
            C = n[:c+1] if c is not None else None
            if C is not None and min(len(F), len(C)) <= max_move:
                if len(C) <= len(F): turns[i][1] = p + C; turns[i+1][1] = n[len(C):]
                else:                turns[i][1] = p[:k+1]; turns[i+1][1] = F + n
                moved = True
        if moved: turns = merge_same(turns); i = max(0, i-1)
        else: i += 1
    return turns

def fmt_time(t):
    t = max(0, int(round(t)))
    h, rem = divmod(t, 3600); m, s = divmod(rem, 60)
    return f"{h}:{m:02d}:{s:02d}" if h else f"{m:02d}:{s:02d}"

def to_records(turns):
    """Turns -> list of dicts: speaker, start, end (seconds), text."""
    recs = []
    for spk, words in turns:
        starts = [w["s"] for w in words if w["s"] is not None]
        ends   = [w["e"] for w in words if w["e"] is not None]
        start = min(starts) if starts else next((w["ss"] for w in words if w["ss"] is not None), 0.0)
        end   = max(ends)   if ends   else next((w["se"] for w in reversed(words) if w["se"] is not None), start)
        recs.append({"speaker": spk, "start": round(start, 2), "end": round(end, 2),
                     "text": " ".join(w["w"] for w in words).strip()})
    return recs

def format_timed(recs):
    return "\n".join(f"[{fmt_time(r['start'])} - {fmt_time(r['end'])}] {r['speaker']}: {r['text']}" for r in recs)

def format_plain(recs):      # format used by eval_transcript.py
    return "\n".join(f"[{r['speaker']}] {r['text']}" for r in recs)

# ---------- pipeline ----------
# 1) Transcribe
model = whisperx.load_model(
    "large-v3", device, compute_type=ctype, language="en",
    asr_options={"initial_prompt": context or None},
    # vad_options={"vad_onset": 0.35, "vad_offset": 0.3},   # uncomment to test lower VAD (variant B)
)
audio = whisperx.load_audio(path)
result = model.transcribe(audio, batch_size=16)
if not result["segments"]:
   raise AudioError("No speech was detected in this recording.")
del model; gc.collect()
if device == "cuda": torch.cuda.empty_cache()

# 2) Align (gives word-level timestamps)
align_model, metadata = whisperx.load_align_model(language_code="en", device=device)
result = whisperx.align(result["segments"], align_model, metadata, audio, device)

# 3) Diarize + assign speakers to words
diarize_model = DiarizationPipeline(token=HF_TOKEN, device=device)
diarize_segments = diarize_model(audio, min_speakers=2, max_speakers=8)
result = whisperx.assign_word_speakers(diarize_segments, result, fill_nearest=True)

# 4) Turns -> fix mid-sentence flips -> records with timestamps
records = to_records(snap_boundaries(build_turns(result)))

timed_transcript = format_timed(records)     # for display / the app / the LLM stages
plain_transcript = format_plain(records)     # for eval_transcript.py
print(timed_transcript)

# 5) Save outputs
with open("transcript_A_timed.txt", "w") as f: f.write(timed_transcript)
with open("transcript_A.txt", "w") as f:      f.write(plain_transcript)
with open("transcript_A.json", "w") as f:     json.dump(records, f, indent=2)

